import {
  copyFile,
  lstat,
  mkdir,
  readdir,
  readFile,
  writeFile,
} from "node:fs/promises";
import { existsSync } from "node:fs";
import {
  basename,
  dirname,
  extname,
  join,
  resolve,
} from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const DEFAULT_TEMPLATE = "lit-shadow";

export const TEMPLATE_NAMES = [
  "lit-shadow",
  "ttsc-shadow",
  "solid-shadow",
  "solid-query-shadow",
  "react-shadow",
  "vanilla-shadow",
] as const;

export type TemplateName = (typeof TEMPLATE_NAMES)[number];

export interface TemplateInfo {
  name: TemplateName;
  title: string;
  framework: string;
  language: string;
  description: string;
  recommendedFor: string;
}

export interface CreateProjectOptions {
  destination: string;
  template?: string;
  force?: boolean;
  local?: boolean;
}

export interface CreateProjectResult {
  dependencyMode: "local" | "published";
  destination: string;
  template: TemplateInfo;
  projectName: string;
  globalName: string;
  projectId: string;
  packageManager: string;
}

interface TemplateReplacements {
  bmklVersion: string;
  globalName: string;
  packageManager: string;
  projectId: string;
  projectName: string;
}

const TEMPLATE_INFOS: TemplateInfo[] = [
  {
    name: "lit-shadow",
    title: "Lit + Shadow DOM",
    framework: "Lit",
    language: "TypeScript",
    description: "A TS-first Vite + Lit starter with Web Components ergonomics.",
    recommendedFor: "Default choice when you want framework structure without TSX.",
  },
  {
    name: "ttsc-shadow",
    title: "ttsc + Shadow DOM",
    framework: "Vanilla + ttsc plugins",
    language: "TypeScript",
    description: "A compiler-aware starter using ttsc lint, strip, paths, and graph.",
    recommendedFor: "Teams that want to showcase or extend ttsc-powered DX.",
  },
  {
    name: "solid-shadow",
    title: "Solid + Shadow DOM",
    framework: "Solid",
    language: "TypeScript / TSX",
    description: "A compact Vite + Solid starter for interactive bookmarklets.",
    recommendedFor: "Small UI overlays and fast widgets with fine-grained reactivity.",
  },
  {
    name: "solid-query-shadow",
    title: "Solid Query + Shadow DOM",
    framework: "Solid + TanStack Query",
    language: "TypeScript / TSX",
    description: "A Solid starter with TanStack Query for cached async page analysis.",
    recommendedFor: "Bookmarklets that cache page reads, refetch DOM state, or add API data.",
  },
  {
    name: "react-shadow",
    title: "React + Shadow DOM",
    framework: "React",
    language: "TypeScript / TSX",
    description: "A Vite + React starter for teams already building React UI.",
    recommendedFor: "React component reuse and familiar app-style workflows.",
  },
  {
    name: "vanilla-shadow",
    title: "Vanilla TS + Shadow DOM",
    framework: "Vanilla",
    language: "TypeScript",
    description: "A minimal Vite + TypeScript starter with no UI framework.",
    recommendedFor: "Tiny actions, page utilities, and dependency-light scripts.",
  },
];

const EXCLUDED_TEMPLATE_ENTRIES = new Set([
  ".DS_Store",
  ".git",
  "dist",
  "node_modules",
]);

const TEXT_TEMPLATE_EXTENSIONS = new Set([
  ".css",
  ".cjs",
  ".html",
  ".js",
  ".json",
  ".jsx",
  ".md",
  ".mjs",
  ".mts",
  ".ts",
  ".tsx",
  ".txt",
  ".yaml",
  ".yml",
]);

const LOCAL_BMKL_PACKAGE_NAMES = [
  "@bmkl/cli",
  "@bmkl/contracts",
  "@bmkl/core",
  "@bmkl/runtime",
  "@bmkl/templates",
  "@bmkl/vite",
] as const;

const GENERATED_WORKSPACE_MARKER = "# Generated by @bmkl/templates.";

export async function listTemplates(): Promise<string[]> {
  return (await readdir(getTemplatesRoot(), { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

export async function listTemplateInfos(): Promise<TemplateInfo[]> {
  const availableTemplates = new Set(await listTemplates());
  return TEMPLATE_INFOS.filter((template) => availableTemplates.has(template.name));
}

export function getTemplateInfo(template: string): TemplateInfo | undefined {
  return TEMPLATE_INFOS.find((info) => info.name === template);
}

export function getTemplateDir(template: string): string {
  if (!getTemplateInfo(template)) {
    throw new Error(
      `Unknown template: ${template}. Choose ${TEMPLATE_NAMES.join(" | ")}.`,
    );
  }
  return join(getTemplatesRoot(), template);
}

export function getTemplatesRoot(): string {
  return join(dirname(fileURLToPath(import.meta.url)), "..", "templates");
}

export async function createProject(
  options: CreateProjectOptions,
): Promise<CreateProjectResult> {
  const templateName = options.template ?? DEFAULT_TEMPLATE;
  const template = getTemplateInfo(templateName);
  if (!template) {
    throw new Error(
      `Unknown template: ${templateName}. Run bmkl templates to list choices.`,
    );
  }

  const templateDir = getTemplateDir(template.name);
  if (!existsSync(templateDir)) {
    throw new Error(`Template not found: ${template.name}`);
  }

  const destination = resolve(options.destination);
  const projectName = toPackageName(basename(destination));
  const globalName = toGlobalName(basename(destination));
  const projectId = `__bmkl_${projectName.replace(/[^a-z0-9]+/g, "_")}__`;
  const { packageManager, version: bmklVersion } =
    await getBmklPackageMetadata();
  const localPackageSpecifiers = options.local
    ? await resolveLocalPackageSpecifiers()
    : undefined;

  await assertWritableDirectory(destination, Boolean(options.force));
  const gitignorePath = join(destination, ".gitignore");
  const pnpmWorkspacePath = join(destination, "pnpm-workspace.yaml");
  await assertGeneratedFilePath(gitignorePath);
  await assertGeneratedFilePath(pnpmWorkspacePath);
  if (localPackageSpecifiers && existsSync(pnpmWorkspacePath)) {
    await assertGeneratedPnpmWorkspace(pnpmWorkspacePath);
  }

  await mkdir(destination, { recursive: true });
  await copyTemplateDirectory(templateDir, destination, {
    bmklVersion,
    globalName,
    packageManager,
    projectId,
    projectName,
  });
  if (localPackageSpecifiers) {
    await applyLocalPackageSpecifiers(destination, localPackageSpecifiers);
  }

  if (!existsSync(gitignorePath)) {
    await writeFile(
      gitignorePath,
      [
        "node_modules/",
        "dist/",
        ".bmkl-dev-cert/",
        ".env*",
        "!.env.example",
        ".DS_Store",
        "*.tsbuildinfo",
        "",
      ].join("\n"),
    );
  }

  if (localPackageSpecifiers || !existsSync(pnpmWorkspacePath)) {
    await writeFile(
      pnpmWorkspacePath,
      createPnpmWorkspace(localPackageSpecifiers),
    );
  }

  return {
    dependencyMode: localPackageSpecifiers ? "local" : "published",
    destination,
    globalName,
    packageManager,
    projectId,
    projectName,
    template,
  };
}

async function resolveLocalPackageSpecifiers(): Promise<Map<string, string>> {
  const templatesPackageRoot = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
  );
  const packagesRoot = dirname(templatesPackageRoot);
  const specifiers = new Map<string, string>();

  for (const name of LOCAL_BMKL_PACKAGE_NAMES) {
    const packageRoot =
      name === "@bmkl/templates"
        ? templatesPackageRoot
        : join(packagesRoot, name.slice("@bmkl/".length));
    const packageJsonPath = join(packageRoot, "package.json");
    let manifest: unknown;
    try {
      manifest = JSON.parse(await readFile(packageJsonPath, "utf8"));
    } catch (error) {
      throw new Error(
        `Local BMKL package is unavailable: ${name}. Build and run the command from a BMKL source checkout.`,
        { cause: error },
      );
    }
    if (!isRecord(manifest) || manifest.name !== name) {
      throw new Error(`Invalid local BMKL package metadata: ${packageJsonPath}`);
    }

    for (const outputPath of getLocalPackageOutputPaths(
      manifest,
      packageJsonPath,
    )) {
      const absoluteOutputPath = resolve(packageRoot, outputPath);
      try {
        if (!(await lstat(absoluteOutputPath)).isFile()) {
          throw new Error("not a regular file");
        }
      } catch (error) {
        throw new Error(
          `Local BMKL package is not fully built: ${name} (${outputPath}). Run pnpm build:packages first.`,
          { cause: error },
        );
      }
    }
    specifiers.set(name, toFileSpecifier(packageRoot));
  }

  return specifiers;
}

async function applyLocalPackageSpecifiers(
  destination: string,
  specifiers: ReadonlyMap<string, string>,
): Promise<void> {
  const packageJsonPath = join(destination, "package.json");
  const manifest: unknown = JSON.parse(await readFile(packageJsonPath, "utf8"));
  if (!isRecord(manifest)) {
    throw new Error(`Invalid generated package metadata: ${packageJsonPath}`);
  }

  for (const sectionName of [
    "dependencies",
    "devDependencies",
    "peerDependencies",
  ]) {
    const section = manifest[sectionName];
    if (!isRecord(section)) {
      continue;
    }
    for (const [name, specifier] of specifiers) {
      if (name in section) {
        section[name] = specifier;
      }
    }
  }

  manifest.private = true;
  await writeFile(packageJsonPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

function createPnpmWorkspace(
  localPackageSpecifiers: ReadonlyMap<string, string> | undefined,
): string {
  const lines = [
    GENERATED_WORKSPACE_MARKER,
    "packages:",
    '  - "."',
    "allowBuilds:",
    "  esbuild: true",
  ];
  if (localPackageSpecifiers) {
    lines.push("overrides:");
    for (const [name, specifier] of localPackageSpecifiers) {
      lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(specifier)}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

async function assertGeneratedPnpmWorkspace(path: string): Promise<void> {
  const contents = await readFile(path, "utf8");
  if (!contents.startsWith(`${GENERATED_WORKSPACE_MARKER}\n`)) {
    throw new Error(
      `Refusing to overwrite an existing pnpm workspace in local mode: ${path}`,
    );
  }
}

function getLocalPackageOutputPaths(
  manifest: Record<string, unknown>,
  packageJsonPath: string,
): string[] {
  const exportsField = manifest.exports;
  const rootExport = isRecord(exportsField) ? exportsField["."] : undefined;
  if (!isRecord(rootExport)) {
    throw new Error(`Invalid local BMKL package exports: ${packageJsonPath}`);
  }

  const outputPaths = [rootExport.types, rootExport.import];
  const bin = manifest.bin;
  if (isRecord(bin)) {
    outputPaths.push(...Object.values(bin));
  }

  if (
    outputPaths.length < 2 ||
    outputPaths.some(
      (path) =>
        typeof path !== "string" ||
        !path.startsWith("./dist/") ||
        path.split("/").includes(".."),
    )
  ) {
    throw new Error(`Invalid local BMKL package outputs: ${packageJsonPath}`);
  }

  return [...new Set(outputPaths as string[])];
}

function toFileSpecifier(target: string): string {
  return pathToFileURL(resolve(target)).href;
}

function isRecord(input: unknown): input is Record<string, unknown> {
  return typeof input === "object" && input !== null && !Array.isArray(input);
}

async function assertWritableDirectory(
  destination: string,
  force: boolean,
): Promise<void> {
  try {
    const info = await lstat(destination);
    if (info.isSymbolicLink()) {
      throw new Error(`Target directory must not be a symbolic link: ${destination}`);
    }
    if (!info.isDirectory()) {
      throw new Error(`Target exists and is not a directory: ${destination}`);
    }

    const entries = await readdir(destination);
    if (entries.length > 0 && !force) {
      throw new Error(`Target directory is not empty: ${destination}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }
    throw error;
  }
}

async function copyTemplateDirectory(
  source: string,
  destination: string,
  replacements: TemplateReplacements,
): Promise<void> {
  const entries = await readdir(source, { withFileTypes: true });
  await mkdir(destination, { recursive: true });

  for (const entry of entries) {
    if (EXCLUDED_TEMPLATE_ENTRIES.has(entry.name)) {
      continue;
    }

    const sourcePath = join(source, entry.name);
    const destinationPath = join(destination, entry.name);

    if (entry.isSymbolicLink()) {
      throw new Error(`Template symbolic links are not allowed: ${sourcePath}`);
    }
    await assertNotSymbolicLink(destinationPath);

    if (entry.isDirectory()) {
      await copyTemplateDirectory(sourcePath, destinationPath, replacements);
      continue;
    }

    if (!entry.isFile()) {
      throw new Error(`Unsupported template entry: ${sourcePath}`);
    }

    await mkdir(dirname(destinationPath), { recursive: true });
    if (isTextTemplateFile(sourcePath)) {
      const text = await readFile(sourcePath, "utf8");
      await writeFile(destinationPath, applyReplacements(text, replacements));
    } else {
      await copyFile(sourcePath, destinationPath);
    }
  }
}

async function assertNotSymbolicLink(path: string): Promise<void> {
  try {
    if ((await lstat(path)).isSymbolicLink()) {
      throw new Error(`Refusing to overwrite a symbolic link: ${path}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }
    throw error;
  }
}

async function assertGeneratedFilePath(path: string): Promise<void> {
  try {
    const info = await lstat(path);
    if (info.isSymbolicLink()) {
      throw new Error(`Refusing to overwrite a symbolic link: ${path}`);
    }
    if (!info.isFile()) {
      throw new Error(`Generated file path must be a regular file: ${path}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }
    throw error;
  }
}

function isTextTemplateFile(path: string): boolean {
  const extension = extname(path);
  if (!extension) {
    return true;
  }

  return TEXT_TEMPLATE_EXTENSIONS.has(extension);
}

function applyReplacements(
  text: string,
  replacements: TemplateReplacements,
): string {
  return text
    .replaceAll("__BMKL_VERSION__", replacements.bmklVersion)
    .replaceAll("__BMKL_PACKAGE_MANAGER__", replacements.packageManager)
    .replaceAll("__BMKL_PROJECT_NAME__", replacements.projectName)
    .replaceAll("__BMKL_GLOBAL_NAME__", replacements.globalName)
    .replaceAll("__BMKL_PROJECT_ID__", replacements.projectId);
}

async function getBmklPackageMetadata(): Promise<{
  packageManager: string;
  version: string;
}> {
  const packageJsonPath = join(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "package.json",
  );
  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as {
    bmkl?: unknown;
    packageManager?: unknown;
    version?: unknown;
  };
  const bmklMetadata = isRecord(packageJson.bmkl)
    ? packageJson.bmkl
    : undefined;
  const packageManager =
    bmklMetadata?.packageManager ?? packageJson.packageManager;

  if (typeof packageJson.version !== "string" || packageJson.version.length === 0) {
    throw new Error(`Invalid @bmkl/templates version in ${packageJsonPath}`);
  }
  if (
    typeof packageManager !== "string" ||
    !/^pnpm@\d+\.\d+\.\d+$/.test(packageManager) ||
    (typeof packageJson.packageManager === "string" &&
      packageJson.packageManager !== packageManager)
  ) {
    throw new Error(
      `Invalid @bmkl/templates packageManager in ${packageJsonPath}`,
    );
  }

  return {
    packageManager,
    version: packageJson.version,
  };
}

function toPackageName(input: string): string {
  const normalized = input
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized || "bookmarklet-app";
}

function toGlobalName(input: string): string {
  const normalized = input
    .replace(/^@/, "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return normalized || "BookmarkletApp";
}
